### ISSUE TITLE
1 is not a prime

### ISSUE THREAD

**Issue by Dream-Master7** [janaindrajit/primePy#5]
Hey there,

I think I found a bug in your code were 

`from primePy import primes`
`print(primes.check(1))`

returns True were it should return False instead.
I suggest changing [this line](https://github.com/janaindrajit/primePy/blob/ee9cc1666bdd6e1e2984ad10d307213e481c937b/primes.py#L20)
from
    `if num==2 or num%2==0:`
to
    `if num == 1 or num==2 or num%2==0:`

**Comment by Dream-Master7** [comment]
Issue is still there. 
Changing the return value of [`if num == 1:`](https://github.com/janaindrajit/primePy/blob/185fb8fc4d2b3a4cd916add038771f26f2c79f67/primes.py#L25) to anything but 1 solves it.

**Comment by Dream-Master7** [comment]
Fixed

**Comment by drarov** [comment]
Hi, this issue is not fixed yet. 
1 is still a prime
